### ISSUE TITLE
Multiline string literals seem to be broken

### ISSUE THREAD

**Issue by forshtat** [protofire/solhint#187]
See: https://github.com/ethereum/solidity/pull/7524
This makes such declarations legal:
```
string = 
"aaa"
"bbb";
```
However, when using solhint with such string I get 
```line 43:4 extraneous input '"bbb"' expecting ';'```

**Comment by fvictorio** [comment]
Hi @forshtat. Thanks for opening this. This is an upstream issue with the parser. Sadly, the parser is in a kind of limbo state: there's the [original repo](https://github.com/federicobond/solidity-parser-antlr), [Consensys's fork](https://github.com/consensys/solidity-parser-antlr) and a [fork of my own](https://github.com/fvictorio/solidity-parser-antlr) that I had to do because Consensys is not being very responsive. Probably Consensys's fork is the correct place to report it for now, so I will do that.

**Comment by forshtat** [comment]
https://github.com/ConsenSys/solidity-parser-antlr/commit/f0de2fcbadffe7c2660dfe16cdf069a0e096e591
