### ISSUE TITLE
Support 0.7.0 constructors without "public" or "internal"

### ISSUE THREAD

**Issue by junderw** [protofire/solhint#240]
Related issues:

Dependency: https://github.com/solidity-parser/parser/issues/23
Related repo: https://github.com/prettier-solidity/prettier-plugin-solidity/issues/310

**Comment by fvictorio** [comment]
Depends on https://github.com/solidity-parser/parser/issues/23

**Comment by junderw** [comment]
I have a local branch with some fixes based off my branch

https://github.com/protofire/solhint/compare/master...junderw:master

**Comment by fvictorio** [comment]
I think there's nothing to do here except upgrading the parser. Our rule of thumb in solhint is to avoid reporting errors that the compiler will raise, which is the case here. The deprecated constructor-syntax is different because there were two valid ways of specifying a constructor, but one of them was recommended over the other. Does that make sense?

**Comment by junderw** [comment]
yes. but currently it will require all 0.7.0 users to always ignore the func-visibility rule for the constructor.

perhaps the func-visibility security rule could check for version and isConstructor, then not throw the error if so.

a linter that "warns" doing something is wrong when that is required by the compiler seems off.

**Comment by fvictorio** [comment]
Oh, I get your point now. Yes, that makes sense.

**Comment by junderw** [comment]
I made a "more-correct" version of the semver compare as well. Here's a PR with the change. Added a test.

https://github.com/protofire/solhint/pull/241
