### ISSUE TITLE
underscores in number literals cause solhint to delete all comments in the file

### ISSUE THREAD

**Issue by moodysalem** [protofire/solhint#255]
repro case:
```solidity
pragma solidity >=0.5.0;

library Math {
    uint16 public constant BIPS_BASE = 10_000; // 10k bips, 100%
}
```

solhint will remove all the comments in the file if it's `10_000` but not if it's `10000`
expect it to not remove comments

**Comment by fvictorio** [comment]
Wait, what? Solhint shouldn't modify your file, unless your are using `--fix`. Is that the case?

**Comment by moodysalem** [comment]
yes, using solhint with prettier, so it is running with fix. either way, just running solhint on the file complains about comments, *iff* you have the underscore

**Comment by fvictorio** [comment]
Hey @moodysalem, this does seem to happen but when using `prettier-plugin-solidity` with the file. Solhint doesn't have a fix for prettier errors. (Wild guess: you have a npm script like `"lint:fix": "solhint --fix **/*.sol && prettier --write **/*.sol"`, and it's the second command that is doing this).

I suggest you open an issue in [prettier-solidity](https://github.com/prettier-solidity/prettier-plugin-solidity/). We know that it has some issues with comments in certain scenarios, and they are somewhat tricky to fix, but it would help us anyway to have the issue reported!

I'm going to close this because I'm pretty sure it's not a problem with solhint, but please re-open if you think it is.

**Comment by moodysalem** [comment]
Thanks @fvictorio, looks like it's already reported here https://github.com/prettier-solidity/prettier-plugin-solidity/issues/355
