### ISSUE TITLE
Feature request: introduce an 'info' error level / allow plugins to override default error level in certain instances

### ISSUE THREAD

**Issue by josh-richardson** [protofire/solhint#271]
I've written a solhint plugin which can be found [here](https://github.com/josh-richardson/solhint-plugin-gsn/blob/master/solhint-plugin-gsn.js) which is designed to work with [gas station network](https://docs.opengsn.org/learn/). It basically replaces instances of `msg.sender` with the GSN-specific implementation which is `_msgSender()`. 

In certain instances the plugin cannot be sure whether or not inserting `_msgSender()` into a Solidity file will cause a compile error or not. In these instances, I'd like to be able to inform the end user if they've used `--fix` that their code has been fixed, but that the plugin has introduced a potential compile issue. Ideally I'd use the reporter to do this, but using it with a `warn` level will be automatically upgraded to an `error` level as the plugin should always be configured with `error` when used in CI pipelines to trigger a non-zero exit code and thus a pipeline failure.

For this reason, I propose that it might be a useful feature to have the ability for plugins to override the error level in situations like these, or have a separate method to show informational data to end users. My [current use ](https://github.com/josh-richardson/solhint-plugin-gsn/blob/master/solhint-plugin-gsn.js#L79) of `console.log` to show this information seems a little ugly.

If the maintainers are amenable to this, I'll submit a PR, but I'd like to get opinions before I go and implement it. Thanks!

**Comment by fvictorio** [comment]
I'm not sure this is a good idea, or at least that the use case justifies the extra complexity.

The underlying problem is that the plugin makes fixes that can break the code, right? I personally think that automatic fixes should only be used when they are "safe", but that's very subjective. If they are not safe, then I think it's mainly a communication issue: it should be properly explained in the plugin's documentation, and a warning in the output also makes sense.

Why do you think that just logging the warning is ugly? It's because it's shown every time the fix is applied?

**Comment by josh-richardson** [comment]
Fair enough. I just thought it would be nicer to have it formatted into the solhint output table, but I see your point of view. I'll close this for now.
