### ISSUE TITLE
import library from node_module

### ISSUE THREAD

**Issue by Drapsag74** [protofire/solhint#32]
I'm trying to use `import "zeppelin-solidity/contracts/token/ERC20/MintableToken.sol";`
but solhint is giving me an error because it can't find the file. How can I indicate a folder for libraries ?
Using a fully relative path works but is quite ugly

**Comment by mariano-aguero** [comment]
Hi @Drapsag74 
I tried to reproduce the problem without success in an empty proyect, I think the error can be due to a problem at the time of compiling the contract (injecting the library) and not solhint. Do you use truffle?   Could you give us some more information about to how to reproduce the error?

**Comment by pablofullana** [comment]
@Drapsag74 I'm closing this one because of lack of feedback. Let us know if you are still facing this issue and have more details, so we can take a deeper look at it. Thanks!
