### ISSUE TITLE
Version 3.3.7 on npm is not in repository

### ISSUE THREAD

**Issue by frangio** [protofire/solhint#333]
The latest version of the npm package is 3.3.7 but I can't find that release in this repository.

**Comment by fvictorio** [comment]
Yes, see [this comment](https://github.com/protofire/solhint/issues/328#issuecomment-1034880584). I don't have write access to this repo anymore for some reason, but I still can publish in npm. Since some people were asking me to update the version of the parser, I did it and published the changes, but couldn't update the code in this repo.

**Comment by frangio** [comment]
Got it. It made me a little paranoid to find this. :innocent: It would be good if you could share a link to the commit that was published. Thanks!

**Comment by fvictorio** [comment]
Oh, sure, [this](https://github.com/fvictorio/solhint/commits/upgrade-parser) is the branch in my fork.

**Comment by fvictorio** [comment]
The repo is up to date now.
