### ISSUE TITLE
Support latest version solc

### ISSUE THREAD

**Issue by julesGoullee** [protofire/solhint#35]
Actually solhint doesnt support:

- event emit : `emit eventName()`
- constructor keyword in place of function name equal to contract name

**Comment by mgarciap** [comment]
Thanks for the feedback. We'll work on that soon. We are looking for contributors. Interested?

**Comment by yarrumretep** [comment]
Also, is there a specific version of antlr that you depend on?  The current version (4.5) generates different javascript than you currently have in the repo when run with `antlr4 lib/grammar/Solidity.g4 -o dork -Dlanguage=JavaScript`, so I'm thinking that it may have been updated since you ran it last.

**Comment by mgarciap** [comment]
That's great @yarrumretep 
Adding @fvictorio and @idrabenia to answer your question.

**Comment by yarrumretep** [comment]
@mgarciap - i've raised a PR that addresses this.
