### ISSUE TITLE
what does two-lines-top-level-separator 	mean?

### ISSUE THREAD

**Issue by iateadonut** [protofire/solhint#45]
Thanks for creating this.  Very helpful.

I couldn't find this in the style guide:

two-lines-top-level-separator | Definition must be surrounded with two blank line indent

What does this mean?

**Comment by iateadonut** [comment]
it just means two lines between pragma soliidty v.x.x; and contract What {

**Comment by fvictorio** [comment]
Sorry for the late response.

You are right. [Here](http://solidity.readthedocs.io/en/v0.4.24/style-guide.html#blank-lines) is the section in the style guide that recommends doing it.

**Comment by PaulRBerg** [comment]
I upgraded to ^3.0.0 recently. Does "two-lines-top-level-separator" not exist anymore? If yes, is there a changelog so see everything that changed?

**Comment by PaulRBerg** [comment]
Nevermind, I found this thread in the meantime:

https://github.com/prettier-solidity/prettier-plugin-solidity/issues/143

My understanding is that the prettier plugin enforces the two lines because of the Solidity documentation. If that is correct, shouldn't solhint follow along? Or is it that with v3, you wanted to be as unopinionated as possible, and delegate most of the formatting to prettier and the user itself?

**Comment by fvictorio** [comment]
That's correct, in v3 we removed all styling rules because they take a lot of time to maintain and are not worth it (at least IMO). So now, if you use prettier-solidity and the [solhint plugin](), then solhint will just let you know if your files differ from how prettier would format them. Does that make sense?

**Comment by PaulRBerg** [comment]
Yup, thanks for confirming @fvictorio. The only issue with the solhint plugin is that it's not up to date, iirc I couldn't use it with solhint v3 and above.

**Comment by fvictorio** [comment]
Really? Oh, I will check that, thanks for letting me know.

**Comment by fvictorio** [comment]
Seems to work fine with v3 for me. Can you open an issue with reproduction steps in the plugin's repo if it isn't working for you?

**Comment by PaulRBerg** [comment]
I was getting this error:

> [solhint] Error: Could not load solhint-plugin-prettier, make sure it's installed.

But I realised that the issue was that I was running a globally-installed version of solhint. When I switched to the local one by prefixing the command with "yarn", things went well.
